---
version: "3.7"
services:
  web:
    image: nginx:1.21.6
    volumes:
      - ./webui:/usr/share/nginx/html
      - ./stratumfarm.crt:/etc/ssl/private/stratumfarm.crt
      - ./stratumfarm.key:/etc/ssl/private/stratumfarm.key
      - ./ssl.conf:/etc/nginx/conf.d/ssl.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
    environment:
      - NGINX_HOST=www.stratum.farm
      - NGINX_PORT=80
